"""ANSYS Fluent case builder — generates journal (.jou) and scheme (.scm) files.

Produces ready-to-run Fluent automation files from HPE sizing results.
Users execute Fluent externally and import results back into HPE.

References:
    ANSYS Fluent User's Guide — TUI command reference.
    ANSYS Fluent Customization Manual — Scheme programming.
"""

from __future__ import annotations

import math
import textwrap
from typing import Any

from hpe.core.models import SizingResult


class FluentCaseBuilder:
    """Generates ANSYS Fluent journal and Scheme files from HPE sizing data."""

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_journal(
        self,
        sizing_result: SizingResult,
        rpm: float,
        flow_rate: float,
        fluid_density: float = 998.0,
        fluid_viscosity: float = 1.003e-3,
        max_iterations: int = 500,
    ) -> str:
        """Generate a Fluent TUI journal (.jou) file.

        The journal automates Fluent from mesh import through solution
        and basic reporting.  It can be executed via:
            fluent 3ddp -g -i pump_hpe.jou

        Args:
            sizing_result: Output from hpe.sizing.
            rpm: Rotational speed [rev/min].
            flow_rate: Volumetric flow rate [m3/s].
            fluid_density: Fluid density [kg/m3].
            fluid_viscosity: Dynamic viscosity [Pa.s].
            max_iterations: Maximum solver iterations.

        Returns:
            Journal file content as a string.
        """
        omega_rad = rpm * math.pi / 30.0
        mass_flow = fluid_density * flow_rate

        # Inlet area for velocity estimate
        mp = sizing_result.meridional_profile
        d_inlet = sizing_result.impeller_d1
        d_hub = mp.get("d1_hub", d_inlet * 0.35)
        a_inlet = math.pi / 4.0 * (d_inlet ** 2 - d_hub ** 2)
        inlet_velocity = flow_rate / a_inlet if a_inlet > 0 else 1.0

        journal = textwrap.dedent(f"""\
            ; =========================================================
            ; ANSYS Fluent Journal (.jou) — generated by HPE
            ; Pump: centrifugal, Nq = {sizing_result.specific_speed_nq:.1f}
            ; D2 = {sizing_result.impeller_d2 * 1000:.1f} mm, RPM = {rpm:.0f}
            ; =========================================================

            ; --- Read mesh ---
            /file/read-case mesh.cas.h5

            ; --- Turbulence model: k-omega SST ---
            /define/models/viscous/kw-sst yes

            ; --- Fluid material: water ---
            /define/materials/change-create water-liquid water-liquid yes \\
              constant {fluid_density:.1f} no no yes \\
              constant {fluid_viscosity:.6e} no no no no no no no

            ; --- Boundary conditions ---

            ; Velocity inlet (normal to boundary)
            /define/boundary-conditions/velocity-inlet inlet \\
              no no yes yes no {inlet_velocity:.6f} no 0 no no yes 5 10

            ; Pressure outlet (0 Pa gauge)
            /define/boundary-conditions/pressure-outlet outlet \\
              yes no 0 no yes no no yes 5 10 yes no no

            ; Wall BCs — blade (no-slip, stationary relative to rotating frame)
            /define/boundary-conditions/wall blade \\
              yes no no no 0 no 0.5 no no no 0 no 0.5

            ; Wall BCs — hub (no-slip, rotating wall)
            /define/boundary-conditions/wall hub \\
              yes motion-bc-moving no no no yes yes \\
              no {omega_rad:.6f} 0 0 1

            ; Wall BCs — shroud (no-slip, counter-rotating wall)
            /define/boundary-conditions/wall shroud \\
              yes motion-bc-moving no no no yes yes \\
              no {-omega_rad:.6f} 0 0 1

            ; --- Cell zone conditions: MRF ---
            /define/cell-zone-conditions/fluid fluid \\
              yes yes no no no \\
              {omega_rad:.6f} 0 0 0 0 0 1

            ; --- Solution monitors ---

            ; Residual monitors
            /solve/monitors/residual/convergence-criteria 1e-5 1e-5 1e-5 1e-5 1e-5 1e-5

            ; Surface monitors
            /solve/monitors/surface/set-monitor pressure-inlet \\
              Area-Weighted Average inlet Pressure yes yes \\
              "pressure-inlet-monitor.out" 1 yes flow-time
            /solve/monitors/surface/set-monitor pressure-outlet \\
              Area-Weighted Average outlet Pressure yes yes \\
              "pressure-outlet-monitor.out" 1 yes flow-time
            /solve/monitors/surface/set-monitor mass-flow-inlet \\
              Mass Flow Rate inlet yes yes \\
              "mass-flow-monitor.out" 1 yes flow-time
            /solve/monitors/surface/set-monitor torque-blade \\
              Moment blade 0 0 0 0 0 1 yes yes \\
              "torque-monitor.out" 1 yes flow-time

            ; --- Initialize and solve ---
            /solve/initialize/hybrid-initialize

            /solve/iterate {max_iterations}

            ; --- Post-processing reports ---
            /report/surface-integrals/area-weighted-avg inlet Pressure yes \\
              "report-pressure-inlet.txt"
            /report/surface-integrals/area-weighted-avg outlet Pressure yes \\
              "report-pressure-outlet.txt"
            /report/surface-integrals/mass-flow-rate inlet outlet yes \\
              "report-mass-flow.txt"
            /report/surface-integrals/moment blade 0 0 0 0 0 1 yes \\
              "report-torque.txt"

            ; --- Save case and data ---
            /file/write-case-data pump_solved.cas.h5 ok

            ; --- Exit ---
            /exit yes
        """)
        return journal

    def generate_scheme(
        self,
        sizing_result: SizingResult,
        rpm: float = 0.0,
        fluid_density: float = 998.0,
    ) -> str:
        """Generate a Fluent Scheme (.scm) file for advanced automation.

        The Scheme file provides hooks for UDF loading, custom
        report definitions, and parametric study automation.

        Args:
            sizing_result: Output from hpe.sizing.
            rpm: Rotational speed [rev/min] (for reference in comments).
            fluid_density: Fluid density [kg/m3].

        Returns:
            Scheme file content as a string.
        """
        omega_rad = rpm * math.pi / 30.0 if rpm > 0 else 0.0
        d2_mm = sizing_result.impeller_d2 * 1000.0

        scheme = textwrap.dedent(f"""\
            ;;; =========================================================
            ;;; ANSYS Fluent Scheme (.scm) — generated by HPE
            ;;; Advanced automation with UDF hooks
            ;;; Nq = {sizing_result.specific_speed_nq:.1f}, D2 = {d2_mm:.1f} mm
            ;;; =========================================================

            ;;; --- Load UDF library (if compiled) ---
            (define (hpe/load-udf)
              (ti-menu-load-string "/define/user-defined/compiled-functions load libudf")
              (display "HPE: UDF library loaded.\\n"))

            ;;; --- Set up custom report definitions ---
            (define (hpe/setup-reports)
              ;; Total pressure difference (head proxy)
              (ti-menu-load-string
                (string-append
                  "/solve/report-definitions/new hpe-delta-p "
                  "surface-areaavg field pressure "
                  "surface-names outlet inlet () "
                  "per-surface? no quit"))
              ;; Torque on blade
              (ti-menu-load-string
                (string-append
                  "/solve/report-definitions/new hpe-torque "
                  "surface-moment surface-names blade () "
                  "moment-center 0 0 0 moment-axis 0 0 1 "
                  "per-surface? no quit"))
              (display "HPE: Report definitions created.\\n"))

            ;;; --- Parametric run helper ---
            (define (hpe/run-parametric rpm-list flow-list)
              "Run a parametric sweep over RPM and flow rate values."
              (for-each
                (lambda (rpm-val)
                  (for-each
                    (lambda (flow-val)
                      (let* ((omega (/ (* rpm-val 3.14159265 ) 30.0))
                             (vel (/ flow-val 1.0)))  ; placeholder area
                        ;; Update MRF angular velocity
                        (ti-menu-load-string
                          (format #f
                            "/define/cell-zone-conditions/fluid fluid yes yes ~
                             no no no ~a 0 0 0 0 0 1"
                            omega))
                        ;; Update inlet velocity
                        (ti-menu-load-string
                          (format #f
                            "/define/boundary-conditions/velocity-inlet inlet ~
                             no no yes yes no ~a no 0"
                            vel))
                        ;; Re-initialize and solve
                        (ti-menu-load-string "/solve/initialize/hybrid-initialize")
                        (ti-menu-load-string "/solve/iterate 500")
                        ;; Export report
                        (ti-menu-load-string
                          (format #f
                            "/file/write-case-data pump_rpm~a_q~a.cas.h5 ok"
                            (inexact->exact (round rpm-val))
                            (inexact->exact (round (* flow-val 10000)))))
                        (display
                          (format #f "HPE: Completed RPM=~a Q=~a\\n"
                            rpm-val flow-val))))
                    flow-list))
                rpm-list))

            ;;; --- Convergence check callback ---
            (define (hpe/check-convergence)
              "Return #t if all residuals are below 1e-5."
              ;; This is a simplified placeholder; real implementation
              ;; would query the residual data structures.
              (let ((res (rpgetvar 'residuals/plot?)))
                (display (format #f "HPE: Convergence check — residual plot: ~a\\n" res))
                #t))

            ;;; --- Entry point ---
            (display "HPE Scheme file loaded.  Available functions:\\n")
            (display "  (hpe/load-udf)           — Load compiled UDF\\n")
            (display "  (hpe/setup-reports)       — Create report definitions\\n")
            (display "  (hpe/run-parametric ...)  — Parametric sweep\\n")
            (display "  (hpe/check-convergence)   — Check residual convergence\\n")
        """)
        return scheme

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _calc_rpm(sizing: SizingResult) -> float:
        """Recover RPM from outlet velocity triangle."""
        u2 = sizing.velocity_triangles["outlet"]["u"]
        return 60.0 * u2 / (math.pi * sizing.impeller_d2)
