"""Generate TURBOdesign1 TD1PerfData.dat compatible performance file.

This format is used by ANSYS TurboGrid and BladeGen to import
performance data from inverse design calculations.

Format:
    Line 1: # TD1 Performance Data — HPE output
    Line 2: # Generated: <date>
    Columns: Flow_m3s  Head_m  Efficiency  NPSHr_m  Power_kW  Nq  D2_mm
"""
from __future__ import annotations
import datetime
from typing import Any


def generate_td1_perfdata(
    sizing_results: list[dict],
    project_name: str = "HPE_Design",
) -> str:
    """Generate TD1PerfData.dat content from a list of sizing results.

    Args:
        sizing_results: List of dicts from run_sizing(), each with
            flow_rate, head, rpm, estimated_efficiency, etc.
        project_name: Project identifier for the file header.

    Returns:
        String content of the .dat file.
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"# TD1PerfData — {project_name}",
        f"# Generated by HPE (Higra Pump Engine) — {now}",
        f"# Compatible with ANSYS BladeGen / TurboGrid import",
        "#",
        "# Flow[m3/s]  Head[m]    RPM      Eta[-]     NPSHr[m]  Power[kW]  Nq     D2[mm]  Z",
        "#" + "-" * 80,
    ]

    for r in sizing_results:
        q = r.get("flow_rate", r.get("specific_speed_nq", 0))
        h = r.get("head", 0)
        n = r.get("rpm", 0)
        eta = r.get("estimated_efficiency", 0)
        npsh = r.get("estimated_npsh_r", 0)
        pwr = r.get("estimated_power", 0) / 1000
        nq = r.get("specific_speed_nq", 0)
        d2 = r.get("impeller_d2", 0) * 1000
        z = r.get("blade_count", 0)

        line = (
            f"  {q:10.6f}  {h:8.3f}  {n:8.1f}  {eta:8.5f}"
            f"  {npsh:8.3f}  {pwr:9.3f}  {nq:6.1f}  {d2:7.2f}  {z:3d}"
        )
        lines.append(line)

    lines.append("#")
    lines.append(f"# End of file — {len(sizing_results)} data points")

    return "\n".join(lines)
