"""CFX-ready package builder -- bundles all ANSYS CFX files into a ZIP.

Creates a downloadable ZIP archive containing CCL setup, PCF parameters,
TurboGrid scripts, blade geometry, and a README with workflow instructions.
"""

from __future__ import annotations

import io
import zipfile

from hpe.core.models import OperatingPoint, SizingResult


def build_cfx_package(
    sizing_result: SizingResult,
    operating_point: OperatingPoint,
) -> bytes:
    """Build a ZIP file containing everything needed for ANSYS CFX.

    Contents:
        setup.ccl          -- CFX-Pre CCL import file
        parameters.pcf     -- Parametric configuration for TurboGrid/TDLink
        blade.geo          -- Blade geometry in structured .geo format
        turbogrid_mesh.py  -- TurboGrid automation script
        run_turbogrid.bat  -- Windows batch launcher
        README.txt         -- Workflow instructions

    Args:
        sizing_result: Output from hpe.sizing.
        operating_point: Design operating point.

    Returns:
        Raw bytes of the ZIP archive.
    """
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # 1. CCL setup file
        from hpe.cfd.ansys_cfx.case_builder import CFXCaseBuilder

        builder = CFXCaseBuilder()
        ccl = builder.generate_ccl(
            sizing_result,
            operating_point.rpm,
            operating_point.flow_rate,
            operating_point.fluid_density,
        )
        zf.writestr("setup.ccl", ccl)

        # 2. PCF file
        from hpe.cfd.pcf_generator import generate_pcf

        pcf = generate_pcf(sizing_result, operating_point)
        zf.writestr("parameters.pcf", pcf)

        # 3. TurboGrid scripts
        from hpe.cfd.turbogrid_wrapper import (
            generate_turbogrid_bat,
            generate_turbogrid_script,
        )

        tg_script = generate_turbogrid_script(
            "blade.geo",
            "mesh.gtm",
            sizing_result.blade_count,
        )
        zf.writestr("turbogrid_mesh.py", tg_script)

        tg_bat = generate_turbogrid_bat("blade.geo", "mesh.gtm")
        zf.writestr("run_turbogrid.bat", tg_bat)

        # 4. Blade geometry (.geo format, in mm)
        from hpe.geometry.runner.export import export_geo_both_surfaces

        geo_data = export_geo_both_surfaces(
            d2=sizing_result.impeller_d2,
            d1=sizing_result.impeller_d1,
            b2=sizing_result.impeller_b2,
            beta1=sizing_result.beta1,
            beta2=sizing_result.beta2,
            blade_count=sizing_result.blade_count,
            unit="mm",
        )
        zf.writestr("blade.geo", geo_data["ps"])
        zf.writestr("blade_ss.geo", geo_data["ss"])

        # 5. README
        q_m3h = operating_point.flow_rate * 3600
        readme = (
            "ANSYS CFX Package -- Generated by HPE (Higra Pump Engine)\n"
            "=========================================================\n"
            "\n"
            "Operating Point:\n"
            f"  Q = {q_m3h:.1f} m3/h\n"
            f"  H = {operating_point.head:.1f} m\n"
            f"  n = {operating_point.rpm:.0f} rpm\n"
            "\n"
            "Sizing Results:\n"
            f"  Nq  = {sizing_result.specific_speed_nq:.1f}\n"
            f"  D2  = {sizing_result.impeller_d2 * 1000:.0f} mm\n"
            f"  Z   = {sizing_result.blade_count} blades\n"
            f"  eta = {sizing_result.estimated_efficiency * 100:.1f}%\n"
            "\n"
            "Files:\n"
            "  setup.ccl          -- Import in CFX-Pre (File > Import CCL)\n"
            "  parameters.pcf     -- Parametric configuration\n"
            "  blade.geo          -- Pressure side blade geometry for TurboGrid\n"
            "  blade_ss.geo       -- Suction side blade geometry\n"
            "  turbogrid_mesh.py  -- TurboGrid automation script\n"
            "  run_turbogrid.bat  -- Windows batch to run TurboGrid\n"
            "\n"
            "Workflow:\n"
            "  1. Open TurboGrid, import blade.geo\n"
            "  2. Run turbogrid_mesh.py for automatic mesh\n"
            "  3. Open CFX-Pre, import mesh + setup.ccl\n"
            "  4. Run CFX-Solver\n"
            "  5. Post-process results\n"
            "\n"
            "Generated by HPE v0.1.0 -- HIGRA Industrial Ltda.\n"
        )
        zf.writestr("README.txt", readme)

    return buf.getvalue()
