"""Structured .pcf file generator for ANSYS TurboGrid / TDLink.

Generates a Parametric Configuration File (.pcf) that TurboGrid and
TDLink can read, containing all key sizing and operating point data
needed to set up a turbomachinery mesh/simulation.

References:
    ANSYS TurboGrid User's Guide -- Parametric studies.
    ANSYS TDLink documentation -- Input file formats.
"""

from __future__ import annotations

from datetime import datetime

from hpe.core.models import OperatingPoint, SizingResult


def generate_pcf(
    sizing_result: SizingResult,
    operating_point: OperatingPoint,
    fluid_name: str = "water",
) -> str:
    """Generate .pcf file content compatible with ANSYS TurboGrid / TDLink.

    Args:
        sizing_result: Output from hpe.sizing.
        operating_point: Design operating point.
        fluid_name: Fluid identifier string.

    Returns:
        String content of the .pcf file.
    """
    mp = sizing_result.meridional_profile

    lines = [
        "# HPE Parametric Configuration File",
        "# Generated by Higra Pump Engine",
        f"# Date: {datetime.now().isoformat()}",
        "",
        "### Machine Type ###",
        f"{mp.get('impeller_type', 'centrifugal')}",
        "",
        "### Rotational Speed (RPM) ###",
        f"{operating_point.rpm}",
        "",
        "### Volume Flow Rate (m3/s) ###",
        f"{operating_point.flow_rate}",
        "",
        "### Head (m) ###",
        f"{operating_point.head}",
        "",
        "### Number of Blades ###",
        f"{sizing_result.blade_count}",
        "",
        "### Inlet Hub Radius (mm) ###",
        f"{mp.get('d1_hub', sizing_result.impeller_d1 * 0.35) * 500}",
        "",
        "### Inlet Shroud Radius (mm) ###",
        f"{sizing_result.impeller_d1 * 500}",
        "",
        "### Outlet Hub Radius (mm) ###",
        f"{sizing_result.impeller_d2 * 500}",
        "",
        "### Outlet Shroud Radius (mm) ###",
        f"{sizing_result.impeller_d2 * 500}",
        "",
        "### Outlet Width b2 (mm) ###",
        f"{sizing_result.impeller_b2 * 1000}",
        "",
        "### Blade Inlet Angle beta1 (deg) ###",
        f"{sizing_result.beta1}",
        "",
        "### Blade Outlet Angle beta2 (deg) ###",
        f"{sizing_result.beta2}",
        "",
        "### Specific Speed Nq ###",
        f"{sizing_result.specific_speed_nq}",
        "",
        "### Estimated Efficiency ###",
        f"{sizing_result.estimated_efficiency}",
        "",
        "### Fluid ###",
        f"{fluid_name}",
        "",
        "### Fluid Density (kg/m3) ###",
        f"{operating_point.fluid_density}",
        "",
        "### Fluid Dynamic Viscosity (Pa.s) ###",
        f"{operating_point.fluid_density * 1.004e-6}",
        "",
        "### Estimated NPSHr (m) ###",
        f"{sizing_result.estimated_npsh_r}",
        "",
        "### Estimated Power (W) ###",
        f"{sizing_result.estimated_power}",
        "",
        "### Slip Factor ###",
        f"{sizing_result.sigma}",
        "",
    ]
    return "\n".join(lines)
