"""Structured .pcf file generator for ANSYS TurboGrid / TDLink.

Generates a Parametric Configuration File (.pcf) that TurboGrid and
TDLink can read, containing all key sizing and operating point data
needed to set up a turbomachinery mesh/simulation.

References:
    ANSYS TurboGrid User's Guide -- Parametric studies.
    ANSYS TDLink documentation -- Input file formats.
"""

from __future__ import annotations

import math
from datetime import datetime

from hpe.core.models import OperatingPoint, SizingResult


def generate_pcf(
    sizing_result: SizingResult,
    operating_point: OperatingPoint,
    fluid_name: str = "water",
) -> str:
    """Generate .pcf file content compatible with ANSYS TurboGrid / TDLink.

    Args:
        sizing_result: Output from hpe.sizing.
        operating_point: Design operating point.
        fluid_name: Fluid identifier string.

    Returns:
        String content of the .pcf file.
    """
    mp = sizing_result.meridional_profile

    # Water at 20 deg C: mu = 1.002e-3 Pa.s (default)
    fluid_viscosity = 1.002e-3

    # Radii in mm (diameter_m * 1000 / 2 = diameter_m * 500)
    d1_hub_m = mp.get("d1_hub", sizing_result.impeller_d1 * 0.35)
    inlet_hub_r_mm = d1_hub_m * 500.0
    inlet_shroud_r_mm = sizing_result.impeller_d1 * 500.0
    # For a radial centrifugal pump, outlet hub and shroud have the same
    # radius (D2/2) -- the passage width b2 is in the axial (Z) direction.
    outlet_hub_r_mm = sizing_result.impeller_d2 * 500.0
    outlet_shroud_r_mm = sizing_result.impeller_d2 * 500.0

    # Blade thickness estimate (2% of D2)
    blade_thickness_mm = max(2.0, sizing_result.impeller_d2 * 1000.0 * 0.02)
    # Leading edge radius estimate (0.5% of D2)
    le_radius_mm = max(0.5, sizing_result.impeller_d2 * 1000.0 * 0.005)

    # Reynolds number: Re = rho * u2 * D2 / mu
    u2 = math.pi * sizing_result.impeller_d2 * operating_point.rpm / 60.0
    re_number = operating_point.fluid_density * u2 * sizing_result.impeller_d2 / fluid_viscosity

    lines = [
        "# HPE Parametric Configuration File",
        "# Generated by Higra Pump Engine",
        f"# Date: {datetime.now().isoformat()}",
        "",
        "### Machine Type ###",
        f"{mp.get('impeller_type', 'centrifugal')}",
        "",
        "### Rotational Speed (RPM) ###",
        f"{operating_point.rpm}",
        "",
        "### Volume Flow Rate (m3/s) ###",
        f"{operating_point.flow_rate}",
        "",
        "### Head (m) ###",
        f"{operating_point.head}",
        "",
        "### Number of Blades ###",
        f"{sizing_result.blade_count}",
        "",
        "### Inlet Hub Radius (mm) ###",
        f"{inlet_hub_r_mm:.1f}",
        "",
        "### Inlet Shroud Radius (mm) ###",
        f"{inlet_shroud_r_mm:.1f}",
        "",
        "### Outlet Hub Radius (mm) ###",
        f"{outlet_hub_r_mm:.1f}",
        "",
        "### Outlet Shroud Radius (mm) ###",
        f"{outlet_shroud_r_mm:.1f}",
        "",
        "### Outlet Width b2 (mm) ###",
        f"{sizing_result.impeller_b2 * 1000:.2f}",
        "",
        "### Blade Inlet Angle beta1 (deg) ###",
        f"{sizing_result.beta1}",
        "",
        "### Blade Outlet Angle beta2 (deg) ###",
        f"{sizing_result.beta2}",
        "",
        "### Blade Thickness Max (mm) ###",
        f"{blade_thickness_mm:.2f}",
        "",
        "### Leading Edge Radius (mm) ###",
        f"{le_radius_mm:.2f}",
        "",
        "### Reynolds Number ###",
        f"{re_number:.0f}",
        "",
        "### Specific Speed Nq ###",
        f"{sizing_result.specific_speed_nq}",
        "",
        "### Estimated Efficiency ###",
        f"{sizing_result.estimated_efficiency}",
        "",
        "### Fluid ###",
        f"{fluid_name}",
        "",
        "### Fluid Density (kg/m3) ###",
        f"{operating_point.fluid_density}",
        "",
        "### Fluid Dynamic Viscosity (Pa.s) ###",
        f"{fluid_viscosity}",
        "",
        "### Estimated NPSHr (m) ###",
        f"{sizing_result.estimated_npsh_r}",
        "",
        "### Estimated Power (W) ###",
        f"{sizing_result.estimated_power}",
        "",
        "### Slip Factor ###",
        f"{sizing_result.sigma}",
        "",
    ]
    return "\n".join(lines)
