"""TurboGrid automation wrapper -- generates batch scripts for mesh generation.

Produces Python automation scripts and Windows batch files that drive
ANSYS TurboGrid in headless (batch) mode from HPE sizing results.

References:
    ANSYS TurboGrid User's Guide -- Scripting and batch mode.
"""

from __future__ import annotations

import textwrap


def generate_turbogrid_script(
    geo_file: str,
    output_mesh: str,
    blade_count: int,
    hub_tip_ratio: float = 0.35,
    boundary_layer_first_height: float = 0.01,
    boundary_layer_growth: float = 1.2,
    boundary_layer_layers: int = 15,
    global_size_factor: float = 1.0,
) -> str:
    """Generate TurboGrid Python/batch automation script.

    The generated script can be executed with::

        cfxtg -batch turbogrid_mesh.py

    Args:
        geo_file: Path to the .geo blade geometry file.
        output_mesh: Path for the exported mesh file (.gtm).
        blade_count: Number of blades (for periodicity).
        hub_tip_ratio: Hub-to-tip radius ratio at inlet.
        boundary_layer_first_height: First cell height [mm].
        boundary_layer_growth: Boundary layer growth rate.
        boundary_layer_layers: Number of boundary layer rows.
        global_size_factor: Global mesh size factor (1.0 = default).

    Returns:
        String content of the TurboGrid automation script.
    """
    script = textwrap.dedent(f"""\
        # TurboGrid Automation Script -- Generated by HPE
        # Run: cfxtg -batch turbogrid_mesh.py

        import os

        # Load geometry
        tg = CFXTurboGridSession()
        tg.readGeometry("{geo_file}")

        # Machine data
        tg.setBladeCount({blade_count})
        tg.setHubTipRatio({hub_tip_ratio})

        # Set topology
        tg.setTopology("ATM Optimized")

        # Mesh sizing
        tg.setGlobalSizeFactor({global_size_factor})
        tg.setBoundaryLayerFirstHeight({boundary_layer_first_height})
        tg.setBoundaryLayerGrowthRate({boundary_layer_growth})
        tg.setBoundaryLayerLayers({boundary_layer_layers})

        # Generate mesh
        tg.generateMesh()

        # Quality report
        tg.printMeshStatistics()

        # Export
        tg.exportMesh("{output_mesh}", format="CFX")

        print("Mesh generation complete: {output_mesh}")

        # Close
        tg.close()
    """)
    return script


def generate_turbogrid_bat(geo_path: str, output_path: str) -> str:
    """Generate a Windows batch file to run TurboGrid in batch mode.

    Args:
        geo_path: Path to the .geo file (or .py script).
        output_path: Path for the output mesh file.

    Returns:
        String content of the .bat file.
    """
    return textwrap.dedent(f"""\
        @echo off
        echo ============================================
        echo  TurboGrid Mesh Generation -- HPE
        echo ============================================
        echo.

        set CFXTG="C:\\Program Files\\ANSYS Inc\\v231\\TurboGrid\\bin\\cfxtg.exe"

        if not exist %CFXTG% (
            echo ERROR: TurboGrid not found at %CFXTG%
            echo Please update the CFXTG path in this script.
            pause
            exit /b 1
        )

        echo Running TurboGrid mesh generation...
        %CFXTG% -batch "turbogrid_mesh.py"
        echo.
        echo Done. Output: {output_path}
        pause
    """)
