"""SU2 solver configuration — Fase 2 CFD Pipeline.

Gera config.cfg para simulações RANS com rotação (turbomáquinas).
Suporta modo direto (análise de performance) e modo adjunto
(otimização de forma com gradiente).

SU2 referência: https://su2code.github.io/docs_v7/

Usage
-----
    from hpe.cfd.su2.config import write_su2_config
    from hpe.core.models import OperatingPoint
    from hpe.geometry.models import RunnerGeometryParams

    path = write_su2_config(
        case_dir=Path("./cases/su2_pump"),
        op=op,
        params=params,
        adjoint=False,
    )
"""

from __future__ import annotations

import math
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from hpe.core.models import OperatingPoint
    from hpe.geometry.models import RunnerGeometryParams

# ---------------------------------------------------------------------------
# Constantes
# ---------------------------------------------------------------------------

_RHO_WATER = 998.2      # kg/m³
_MU_WATER = 1.003e-3    # Pa·s
_NU_WATER = _MU_WATER / _RHO_WATER


def write_su2_config(
    case_dir: Path,
    op: "OperatingPoint",
    params: "RunnerGeometryParams",
    adjoint: bool = False,
    mesh_filename: str = "runner_mesh.su2",
    n_iter: int = 1000,
) -> Path:
    """Escrever config.cfg para SU2 RANS com rotação de bomba centrífuga.

    Configuração gerada:
      - Solver: RANS incompressível (INC_RANS)
      - Modelo de turbulência: k-ω SST
      - Rotação: ROTATING_FRAME com omega no eixo Z
      - Fluido: água incompressível (Newtoniano)
      - Objetivo (adjunto): minimizar TOTAL_PRESSURE_LOSS
      - Problema: DIRECT ou CONTINUOUS_ADJOINT

    Parameters
    ----------
    case_dir : Path
        Diretório onde escrever o arquivo config.cfg.
    op : OperatingPoint
        Ponto de operação (Q, H, rpm).
    params : RunnerGeometryParams
        Parâmetros geométricos do rotor (para escala de referência).
    adjoint : bool
        Se True, gera configuração para solver adjunto contínuo.
    mesh_filename : str
        Nome do arquivo de malha SU2 (.su2).
    n_iter : int
        Número máximo de iterações.

    Returns
    -------
    Path
        Caminho do arquivo config.cfg gerado.
    """
    case_dir = Path(case_dir)
    case_dir.mkdir(parents=True, exist_ok=True)

    # Parâmetros físicos
    omega_rad_s = op.rpm * math.pi / 30.0
    nu = getattr(op, "fluid_viscosity", _MU_WATER) / getattr(op, "fluid_density", _RHO_WATER)
    rho = getattr(op, "fluid_density", _RHO_WATER)

    # Velocidade de entrada (inlet) a partir de Q e área
    d1 = params.d1
    d1h = params.d1_hub
    a_inlet = math.pi / 4.0 * (d1**2 - d1h**2)
    u_inlet = op.flow_rate / max(a_inlet, 1e-9)

    # Velocidade de referência = velocidade periférica máxima
    u_ref = omega_rad_s * params.d2 / 2.0

    # Reynolds baseado em D2
    re = u_ref * params.d2 / nu if nu > 0 else 1e6

    # Modo: DIRECT ou CONTINUOUS_ADJOINT
    math_problem = "CONTINUOUS_ADJOINT" if adjoint else "DIRECT"
    obj_func = "TOTAL_PRESSURE_LOSS" if adjoint else "DRAG"

    # Turbulência: intensidade e escala de comprimento
    turb_intensity = 0.05
    k_init = 1.5 * (u_inlet * turb_intensity) ** 2
    omega_turb = math.sqrt(k_init) / (0.09**0.25 * 0.1 * d1) if d1 > 0 else 100.0

    content = f"""% =========================================================
% HPE — SU2 Configuration File
% Solver: INC_RANS (Incompressible RANS)
% Problem: {math_problem}
% Generated by hpe.cfd.su2.config
% =========================================================

% --- Problem Definition ---
SOLVER= INC_RANS
KIND_TURB_MODEL= SST
MATH_PROBLEM= {math_problem}
RESTART_SOL= NO

% --- Rotating Frame (MRF) ---
ROTATING_FRAME= YES
ROTATION_RATE= 0.0 0.0 {omega_rad_s:.8f}
FREESTREAM_PRESSURE= 101325.0
FREESTREAM_TEMPERATURE= 293.15

% --- Incompressible fluid (water) ---
INC_DENSITY_MODEL= CONSTANT
INC_ENERGY_EQUATION= NO
INC_DENSITY_INIT= {rho:.4f}
INC_VELOCITY_INIT= ( {u_inlet:.6f} 0.0 0.0 )
VISCOSITY_MODEL= CONSTANT_VISCOSITY
MU_CONSTANT= {_MU_WATER:.8e}

% --- Reference Values ---
REF_DIMENSIONALIZATION= DIMENSIONAL
REF_ORIGIN_MOMENT_X= 0.0
REF_ORIGIN_MOMENT_Y= 0.0
REF_ORIGIN_MOMENT_Z= 0.0
REF_LENGTH= {params.d2:.6f}
REF_AREA= {a_inlet:.8e}

% --- Mesh File ---
MESH_FILENAME= {mesh_filename}
MESH_FORMAT= SU2
MESH_OUT_FILENAME= mesh_out.su2

% --- Boundary Conditions ---
MARKER_HEATFLUX= ( rotorWalls, 0.0, statorWalls, 0.0 )
MARKER_INLET= ( inlet, 293.15, {u_inlet:.6f}, 1.0, 0.0, 0.0 )
MARKER_OUTLET= ( outlet, 101325.0 )
MARKER_SYM= ( symmetry )

% --- Turbulence BCs ---
MARKER_TURBOMACHINERY= ( rotatingZone_to_stator )
FREESTREAM_TURBULENCEINTENSITY= {turb_intensity:.4f}
FREESTREAM_TURB2LAMVISCRATIO= 10.0

% --- SST Model ---
SST_OPTIONS= V1994m

% --- Numerical Method ---
NUM_METHOD_GRAD= GREEN_GAUSS
CFL_NUMBER= 25.0
CFL_ADAPT= YES
CFL_ADAPT_PARAM= ( 0.3, 2.0, 10.0, 1000.0 )
MAX_DELTA_TIME= 1e6

% --- Linear Solver ---
LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ILU_FILL_IN= 0
LINEAR_SOLVER_ERROR= 1E-10
LINEAR_SOLVER_ITER= 10

% --- Convective Schemes ---
CONV_NUM_METHOD_FLOW= FDS
MUSCL_FLOW= YES
SLOPE_LIMITER_FLOW= VENKATAKRISHNAN
VENKAT_LIMITER_COEFF= 0.1
JST_SENSOR_COEFF= ( 0.5, 0.02 )

CONV_NUM_METHOD_TURB= SCALAR_UPWIND
MUSCL_TURB= NO

% --- Convergence ---
CONV_RESIDUAL_MINVAL= -12
CONV_STARTITER= 25
CONV_CAUCHY_ELEMS= 100
CONV_CAUCHY_EPS= 1E-6
ITER= {n_iter}

% --- Objective Function (adjoint) ---
OBJECTIVE_FUNCTION= {obj_func}
OBJECTIVE_WEIGHT= 1.0

% --- Output ---
OUTPUT_FILES= RESTART, PARAVIEW, SURFACE_PARAVIEW
CONV_FILENAME= history
RESTART_FILENAME= restart_flow.dat
VOLUME_FILENAME= flow
SURFACE_FILENAME= surface_flow
OUTPUT_WRT_FREQ= 100
SCREEN_WRT_FREQ_INNER= 1
SCREEN_OUTPUT= ( INNER_ITER, WALL_TIME, RMS_PRESSURE, RMS_VELOCITY-X, RMS_TKE, TOTAL_PRESSURE_LOSS )
HISTORY_OUTPUT= ( ITER, RMS_RES, AERO_COEFF, FLOW_COEFF )
"""

    if adjoint:
        content += f"""
% =========================================================
% Adjoint-specific settings
% =========================================================
SENS_SMOOTHING= NO
GRAD_OBJFUNC_FILENAME= of_grad.dat
SOLUTION_ADJ_FILENAME= solution_adj.dat
RESTART_ADJ_FILENAME= restart_adj.dat
VOLUME_ADJ_FILENAME= adjoint
SURFACE_ADJ_FILENAME= surface_adjoint
"""

    path = case_dir / "config.cfg"
    path.write_text(content, encoding="utf-8")
    return path
